## Keras

In [ ]:
#some data
import pandas as pd

data = pd.read_csv('/datasets/train_data_n.csv')
features = data.drop('target', axis=1)
target = data['target']

### Linear Regression in Keras

In [ ]:
#in sklearn
# import from sklearn
from sklearn.linear_model import LinearRegression

# create the model
model = LinearRegression()

# train the model
model.fit(features, target)

In [ ]:
#in keras
# import Keras
from tensorflow import keras

# create the model
model = keras.models.Sequential()
# indicate how the neural network is arranged
model.add(keras.layers.Dense(units=1, input_dim=features.shape[1]))
# indicate how the neural network is trained
model.compile(loss='mean_squared_error', optimizer='sgd')

# train the model
model.fit(features, target)

- Let's set the model class to Sequential. 
- This class is used for models with sequential layers. Layer is a set of neurons that share the same input and output.

- The keras.layers.Dense() command creates one layer of neurons. 
- "Dense" means that every input will be connected to every neuron, or output. 
- The units parameter sets the number of neurons in the layer, and input_dim sets the number of inputs in the layer. 
- Note that this parameter doesn't take the bias into account.
- To add the fully connected layer to the model, call the model.add() method:
- `model.compile` - It prepares the model for training. 
- Specify MSE as the regression task loss function for the loss parameter. 
-Set the gradient descent method for the optimizer='sgd' parameter. Remember, we'll be training neural networks using SGD.

*Layers where all inputs are connected to all neurons are called **fully connected layers**.*

`keras.layers.Dense(units=2, input_dim=3)` - two neurons and three inputs

In [ ]:
import pandas as pd
from tensorflow import keras

data = pd.read_csv('/datasets/train_data_n.csv')
features = data.drop('target', axis=1)
target = data['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features.shape[1]))
model.compile(loss='mean_squared_error', optimizer='sgd')
model.fit(features, target, verbose=2)

In [ ]:
#epochs = how many times has our data passed through the algorithm) to get the MSE to be less than 6.55.
model.fit(features, target, verbose=2, epochs=5)

In [ ]:
#Find the loss function value for the validation set.
import pandas as pd
from tensorflow import keras

data_train = pd.read_csv('/datasets/train_data_n.csv')
features_train = data_train.drop('target', axis=1)
target_train = data_train['target']

data_valid = pd.read_csv('/datasets/test_data_n.csv')
features_valid = data_valid.drop('target', axis=1)
target_valid = data_valid['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1]))
model.compile(loss='mean_squared_error', optimizer='sgd')
model.fit(features_train, target_train, validation_data=(features_valid, target_valid), epochs=5, verbose=2)

### Logistic Regression in Keras

In [ ]:
#Apply the activation function to the fully connected layer:
keras.layers.Dense(units=1, input_dim=features_train.shape[1], activation='sigmoid')

In [ ]:
#Change the loss function from MSE to binary_crossentropy;
model.compile(loss='binary_crossentropy', optimizer='sgd')

In [ ]:
import pandas as pd
from tensorflow import keras

df = pd.read_csv('/datasets/train_data_n.csv')
df['target'] = (df['target'] > df['target'].median()).astype(int)
features_train = df.drop('target', axis=1)
target_train = df['target']

df_val = pd.read_csv('/datasets/test_data_n.csv')
df_val['target'] = (df_val['target'] > df['target'].median()).astype(int)
features_valid = df_val.drop('target', axis=1)
target_valid = df_val['target']

# < write code here >
model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1], activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='sgd')
model.fit(features_train, target_train, validation_data=(features_valid, target_valid), verbose=2, epochs=5)

In [ ]:
#model's accuracy using validation data
import pandas as pd
from tensorflow import keras
from sklearn.metrics import accuracy_score


df = pd.read_csv('/datasets/train_data_n.csv')
df['target'] = (df['target'] > df['target'].median()).astype(int)
features_train = df.drop('target', axis=1)
target_train = df['target']

df_val = pd.read_csv('/datasets/test_data_n.csv')
df_val['target'] = (df_val['target'] > df['target'].median()).astype(int)
features_valid = df_val.drop('target', axis=1)
target_valid = df_val['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1], 
                             activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='sgd')
model.fit(features_train, target_train, epochs=5, verbose=0,
          validation_data=(features_valid, target_valid))


# < write code here >
predictions = model.predict(features_valid) > 0.5
#print(predictions)
score = accuracy_score(predictions, target_valid)
print("Accuracy:", score)# < write code here >)

In [ ]:
#trace quality at each epoch
import pandas as pd
from tensorflow import keras
from sklearn.metrics import accuracy_score


df = pd.read_csv('/datasets/train_data_n.csv')
df['target'] = (df['target'] > df['target'].median()).astype(int)
features_train = df.drop('target', axis=1)
target_train = df['target']

df_val = pd.read_csv('/datasets/test_data_n.csv')
df_val['target'] = (df_val['target'] > df['target'].median()).astype(int)
features_valid = df_val.drop('target', axis=1)
target_valid = df_val['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1], 
                             activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['acc'])
model.fit(features_train, target_train, epochs=10, verbose=2,
          validation_data=(features_valid, target_valid))

### Fully Connected Neural Networks in Keras

In [ ]:
import pandas as pd
from tensorflow import keras
from sklearn.metrics import accuracy_score


df = pd.read_csv('/datasets/train_data_n.csv')
df['target'] = (df['target'] > df['target'].median()).astype(int)
features_train = df.drop('target', axis=1)
target_train = df['target']

df_val = pd.read_csv('/datasets/test_data_n.csv')
df_val['target'] = (df_val['target'] > df['target'].median()).astype(int)
features_valid = df_val.drop('target', axis=1)
target_valid = df_val['target']

model = keras.models.Sequential()
# < write code here >
#adding hidden layers with different neurons
model.add(keras.layers.Dense(units=10, activation='sigmoid',input_dim=features_train.shape[1]))
model.add(keras.layers.Dense(units=1, activation='sigmoid', input_dim=features_train.shape[1]))

model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['acc'])

model.fit(features_train, target_train, epochs=10, verbose=2,
          validation_data=(features_valid, target_valid))

### Working with Images in Python

In [1]:
import numpy as np
from PIL import Image

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)
print(array)


FileNotFoundError: [Errno 2] No such file or directory: '/datasets/ds_cv_images/face.png'

In [ ]:
#we get a 2-D array
[[255 255 255 255 237 217 239 255 255 255 255 255 255]
 [255 255 190  75  29  29  30  81 198 255 255 255 255]
 [255 147  30  29  29  29  29  29  31 160 255 255 255]
 [185  29  29  29  29  29  29  29  29  31 198 255 255]
 [ 61  29  29  29  29  29  29  29  29  29  74 255 255]
 [108 121 121 121 121 121 121 121 121 121 102 219 255]
 [250 255 255 255 255 255 255 255 255 255 238 107 168]
 [255 238 153 150 152 244 201 152 150 178 253 103 144]
 [248 243 121 108 114 225 184 130 112 154 235 103  62]
 [197 255 227 168 231 149 230 196 179 251 183  29  29]
 [105 255 255 219 195 191 184 195 235 255  91  29  29]
 [ 30 187 255 234 218 218 218 218 243 174  29  29  29]
 [ 29  38 180 255 255 255 255 255 169  35  29  29  29]
 [ 29  29  29  82 153 174 150  76  29  29  29  29  29]
 [ 29  29  29  29  29  29  29  29  29  29  29  29  29]]

In [ ]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

# < write code here >
plt.imshow(array)

In [5]:
import matplotlib.pyplot as plt

In [ ]:
#set color to balck and white
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

plt.imshow(array, cmap='gray')# < write code here >)
# < write code here >
plt.colorbar()

In [8]:
import numpy as np

In [9]:
#repaint corners
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

# < write code here >
#print(array.shape)
array[0][0] = 0
array[14][12] = 255
#print(array)

plt.imshow(array, cmap='gray')
plt.colorbar()

In [ ]:
#normalize the scale
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

# < write code here >
array = array / 255
#print(array)

plt.imshow(array, cmap='gray')
plt.colorbar()

### Color images

In [10]:
np.array([[0, 255],
                    [255, 0]])

array([[  0, 255],
       [255,   0]])

In [11]:
np.array([[[0, 255, 0], [128, 0, 255]], 
                    [[12, 89, 0], [5,  89, 245]]])


array([[[  0, 255,   0],
        [128,   0, 255]],

       [[ 12,  89,   0],
        [  5,  89, 245]]])

In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/cat.jpg')
array = np.array(image)

# < write code here >
print(array.shape)
#print(array)
#print(array.ndim)

In [ ]:
#output the red channel only
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/cat.jpg')
array = np.array(image)

red_channel =array[:,:,0] 
# < write code here >

plt.imshow(red_channel)
plt.colorbar()

### Image Classification

-  We need to build a ten-class classifier for the clothing store aggregator.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np


features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')

print("Train:", features_train.shape)# < write code here >)
print("Test:", features_test.shape)# < write code here >)

print("First image class:", target_train[0])# < write code here >)
plt.imshow(features_train[0], cmap='gray')# < write code here >)

In [15]:
x = np.array([[[0, 255, 0], [128, 0, 255]], 
                    [[12, 89, 0], [5,  89, 245]]])

In [18]:
x.shape

(2, 2, 3)

In [21]:
y = np.reshape(x, (3,4))

In [22]:
y.shape

(3, 4)

### 3D to 2D

In [ ]:
import matplotlib.pyplot as plt
import numpy as np


features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')

# < write code here >
features_train = features_train.reshape(features_train.shape[0], 28 * 28)
features_test = features_test.reshape(features_test.shape[0], 28 * 28)

print("Train:", features_train.shape)
print("Test:", features_test.shape)

### Build and train a neural network. First, create a logistic regression with ten classes in Keras

In [ ]:
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np


features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')

features_train = features_train.reshape(features_train.shape[0], 28 * 28)
features_test = features_test.reshape(features_test.shape[0], 28 * 28)

model = keras.models.Sequential()# < write code here >
model.add(keras.layers.Dense(units=10, activation='softmax', input_dim=28*28))
model.compile(loss='sparse_categorical_crossentropy', optimizer='sgd', metrics=['acc'])
model.fit(features_train, target_train, epochs=1, verbose=2,
          validation_data=(features_test, target_test))

# < write code here >

#model.fit(# < write code here >)