## Keras

In [1]:
!pip install keras

In [4]:
!pip install tensorflow

ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\numpy\\~ore\\_multiarray_tests.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.




  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4835 sha256=26f1514b27e5276ed152073afc0a71bbc095506e29131947f57173962d6b310e
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\3f\e3\ec\8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2
Successfully built termcolor
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2


In [10]:
!pip install --user tensorflow

In [11]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [3]:
from keras.models import Sequential

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

In [ ]:
#some data
import pandas as pd

data = pd.read_csv('/datasets/train_data_n.csv')
features = data.drop('target', axis=1)
target = data['target']

### Linear Regression in Keras

In [ ]:
#in sklearn
# import from sklearn
from sklearn.linear_model import LinearRegression

# create the model
model = LinearRegression()

# train the model
model.fit(features, target)

In [ ]:
#in keras
# import Keras
from tensorflow import keras

# create the model
model = keras.models.Sequential()
# indicate how the neural network is arranged
model.add(keras.layers.Dense(units=1, input_dim=features.shape[1]))
# indicate how the neural network is trained
model.compile(loss='mean_squared_error', optimizer='sgd')

# train the model
model.fit(features, target)

- Let's set the model class to Sequential. 
- This class is used for models with sequential layers. Layer is a set of neurons that share the same input and output.

- The keras.layers.Dense() command creates one layer of neurons. 
- "Dense" means that every input will be connected to every neuron, or output. 
- The units parameter sets the number of neurons in the layer, and input_dim sets the number of inputs in the layer. 
- Note that this parameter doesn't take the bias into account.
- To add the fully connected layer to the model, call the model.add() method:
- `model.compile` - It prepares the model for training. 
- Specify MSE as the regression task loss function for the loss parameter. 
-Set the gradient descent method for the optimizer='sgd' parameter. Remember, we'll be training neural networks using SGD.

*Layers where all inputs are connected to all neurons are called **fully connected layers**.*

`keras.layers.Dense(units=2, input_dim=3)` - two neurons and three inputs

In [ ]:
import pandas as pd
from tensorflow import keras

data = pd.read_csv('/datasets/train_data_n.csv')
features = data.drop('target', axis=1)
target = data['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features.shape[1]))
model.compile(loss='mean_squared_error', optimizer='sgd')
model.fit(features, target, verbose=2)

In [ ]:
#epochs = how many times has our data passed through the algorithm) to get the MSE to be less than 6.55.
model.fit(features, target, verbose=2, epochs=5)

In [ ]:
#Find the loss function value for the validation set.
import pandas as pd
from tensorflow import keras

data_train = pd.read_csv('/datasets/train_data_n.csv')
features_train = data_train.drop('target', axis=1)
target_train = data_train['target']

data_valid = pd.read_csv('/datasets/test_data_n.csv')
features_valid = data_valid.drop('target', axis=1)
target_valid = data_valid['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1]))
model.compile(loss='mean_squared_error', optimizer='sgd')
model.fit(features_train, target_train, validation_data=(features_valid, target_valid), epochs=5, verbose=2)

### Logistic Regression in Keras

In [ ]:
#Apply the activation function to the fully connected layer:
keras.layers.Dense(units=1, input_dim=features_train.shape[1], activation='sigmoid')

In [ ]:
#Change the loss function from MSE to binary_crossentropy;
model.compile(loss='binary_crossentropy', optimizer='sgd')

In [ ]:
import pandas as pd
from tensorflow import keras

df = pd.read_csv('/datasets/train_data_n.csv')
df['target'] = (df['target'] > df['target'].median()).astype(int)
features_train = df.drop('target', axis=1)
target_train = df['target']

df_val = pd.read_csv('/datasets/test_data_n.csv')
df_val['target'] = (df_val['target'] > df['target'].median()).astype(int)
features_valid = df_val.drop('target', axis=1)
target_valid = df_val['target']

# < write code here >
model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1], activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='sgd')
model.fit(features_train, target_train, validation_data=(features_valid, target_valid), verbose=2, epochs=5)

In [ ]:
#model's accuracy using validation data
import pandas as pd
from tensorflow import keras
from sklearn.metrics import accuracy_score


df = pd.read_csv('/datasets/train_data_n.csv')
df['target'] = (df['target'] > df['target'].median()).astype(int)
features_train = df.drop('target', axis=1)
target_train = df['target']

df_val = pd.read_csv('/datasets/test_data_n.csv')
df_val['target'] = (df_val['target'] > df['target'].median()).astype(int)
features_valid = df_val.drop('target', axis=1)
target_valid = df_val['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1], 
                             activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='sgd')
model.fit(features_train, target_train, epochs=5, verbose=0,
          validation_data=(features_valid, target_valid))


# < write code here >
predictions = model.predict(features_valid) > 0.5
#print(predictions)
score = accuracy_score(predictions, target_valid)
print("Accuracy:", score)# < write code here >)

In [ ]:
#trace quality at each epoch
import pandas as pd
from tensorflow import keras
from sklearn.metrics import accuracy_score


df = pd.read_csv('/datasets/train_data_n.csv')
df['target'] = (df['target'] > df['target'].median()).astype(int)
features_train = df.drop('target', axis=1)
target_train = df['target']

df_val = pd.read_csv('/datasets/test_data_n.csv')
df_val['target'] = (df_val['target'] > df['target'].median()).astype(int)
features_valid = df_val.drop('target', axis=1)
target_valid = df_val['target']

model = keras.models.Sequential()
model.add(keras.layers.Dense(units=1, input_dim=features_train.shape[1], 
                             activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['acc'])
model.fit(features_train, target_train, epochs=10, verbose=2,
          validation_data=(features_valid, target_valid))

### Fully Connected Neural Networks in Keras

In [ ]:
import pandas as pd
from tensorflow import keras
from sklearn.metrics import accuracy_score


df = pd.read_csv('/datasets/train_data_n.csv')
df['target'] = (df['target'] > df['target'].median()).astype(int)
features_train = df.drop('target', axis=1)
target_train = df['target']

df_val = pd.read_csv('/datasets/test_data_n.csv')
df_val['target'] = (df_val['target'] > df['target'].median()).astype(int)
features_valid = df_val.drop('target', axis=1)
target_valid = df_val['target']

model = keras.models.Sequential()
# < write code here >
#adding hidden layers with different neurons
model.add(keras.layers.Dense(units=10, activation='sigmoid',input_dim=features_train.shape[1]))
model.add(keras.layers.Dense(units=1, activation='sigmoid', input_dim=features_train.shape[1]))

model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['acc'])

model.fit(features_train, target_train, epochs=10, verbose=2,
          validation_data=(features_valid, target_valid))

### Working with Images in Python

In [1]:
import numpy as np
from PIL import Image

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)
print(array)


FileNotFoundError: [Errno 2] No such file or directory: '/datasets/ds_cv_images/face.png'

In [ ]:
#we get a 2-D array
[[255 255 255 255 237 217 239 255 255 255 255 255 255]
 [255 255 190  75  29  29  30  81 198 255 255 255 255]
 [255 147  30  29  29  29  29  29  31 160 255 255 255]
 [185  29  29  29  29  29  29  29  29  31 198 255 255]
 [ 61  29  29  29  29  29  29  29  29  29  74 255 255]
 [108 121 121 121 121 121 121 121 121 121 102 219 255]
 [250 255 255 255 255 255 255 255 255 255 238 107 168]
 [255 238 153 150 152 244 201 152 150 178 253 103 144]
 [248 243 121 108 114 225 184 130 112 154 235 103  62]
 [197 255 227 168 231 149 230 196 179 251 183  29  29]
 [105 255 255 219 195 191 184 195 235 255  91  29  29]
 [ 30 187 255 234 218 218 218 218 243 174  29  29  29]
 [ 29  38 180 255 255 255 255 255 169  35  29  29  29]
 [ 29  29  29  82 153 174 150  76  29  29  29  29  29]
 [ 29  29  29  29  29  29  29  29  29  29  29  29  29]]

In [ ]:
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

# < write code here >
plt.imshow(array)

In [5]:
import matplotlib.pyplot as plt

In [ ]:
#set color to balck and white
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

plt.imshow(array, cmap='gray')# < write code here >)
# < write code here >
plt.colorbar()

In [8]:
import numpy as np

In [9]:
#repaint corners
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

# < write code here >
#print(array.shape)
array[0][0] = 0
array[14][12] = 255
#print(array)

plt.imshow(array, cmap='gray')
plt.colorbar()

In [ ]:
#normalize the scale
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/face.png')
array = np.array(image)

# < write code here >
array = array / 255
#print(array)

plt.imshow(array, cmap='gray')
plt.colorbar()

### Color images

In [10]:
np.array([[0, 255],
                    [255, 0]])

array([[  0, 255],
       [255,   0]])

In [11]:
np.array([[[0, 255, 0], [128, 0, 255]], 
                    [[12, 89, 0], [5,  89, 245]]])


array([[[  0, 255,   0],
        [128,   0, 255]],

       [[ 12,  89,   0],
        [  5,  89, 245]]])

In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/cat.jpg')
array = np.array(image)

# < write code here >
print(array.shape)
#print(array)
#print(array.ndim)

In [ ]:
#output the red channel only
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

image = Image.open('/datasets/ds_cv_images/cat.jpg')
array = np.array(image)

red_channel =array[:,:,0] 
# < write code here >

plt.imshow(red_channel)
plt.colorbar()

### Image Classification

-  We need to build a ten-class classifier for the clothing store aggregator.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np


features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')

print("Train:", features_train.shape)# < write code here >)
print("Test:", features_test.shape)# < write code here >)

print("First image class:", target_train[0])# < write code here >)
plt.imshow(features_train[0], cmap='gray')# < write code here >)

In [1]:
import numpy as np

In [7]:
lis = [[0, 255, 0], [128, 0, 255]]
a_lis = np.array(lis)
type(a_lis)
a_lis.shape
len(a_lis)

2

In [15]:
x = np.array([[[0, 255, 0], [128, 0, 255]], 
                    [[12, 89, 0], [5,  89, 245]]])

In [18]:
x.shape

(2, 2, 3)

In [21]:
y = np.reshape(x, (3,4))

In [22]:
y.shape

(3, 4)

### 3D to 2D

In [ ]:
import matplotlib.pyplot as plt
import numpy as np


features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')

# < write code here >
features_train = features_train.reshape(features_train.shape[0], 28 * 28)
features_test = features_test.reshape(features_test.shape[0], 28 * 28)

print("Train:", features_train.shape)
print("Test:", features_test.shape)

### Build and train a neural network. First, create a logistic regression with ten classes in Keras

In [ ]:
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np


features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')

features_train = features_train.reshape(features_train.shape[0], 28 * 28)
features_test = features_test.reshape(features_test.shape[0], 28 * 28)

model = keras.models.Sequential()# < write code here >
model.add(keras.layers.Dense(units=10, activation='softmax', input_dim=28*28))
model.compile(loss='sparse_categorical_crossentropy', optimizer='sgd', metrics=['acc'])
model.fit(features_train, target_train, epochs=1, verbose=2,
          validation_data=(features_test, target_test))

# < write code here >

#model.fit(# < write code here >)

### Multi-layer Network Training

In [ ]:
#how to train a model on the server
#pretest the code
#1. loading the training sample
def load_train(path):
    ...

In [ ]:
def load_train(path):
    features_train = np.load(path + 'train_features.npy')
    target_train = np.load(path + 'train_target.npy')
    features_train = features_train.reshape(features_train.shape[0], 28 * 28) / 255.
    return features_train, target_train

In [ ]:
#Create a model for a neural network and use the return command to return it
#Use the input_shape parameter to specify the data size in the first layer.
def create_model(input_shape):
    model = Sequential()
    model.add(Dense(10, input_shape=input_shape, activation='softmax'))
    model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy',
                  metrics=['acc'])

    return model

In [ ]:
#launch the model
def train_model(model, train_data, test_data, batch_size, epochs,
                steps_per_epoch, validation_steps):
    ...

In [ ]:
def train_model(model, train_data, test_data, batch_size=32, epochs=5,
                steps_per_epoch=None, validation_steps=None):

    features_train, target_train = train_data
    features_test, target_test = test_data
    model.fit(features_train, target_train, 
              validation_data=(features_test, target_test),
              batch_size=batch_size, epochs=epochs,
              steps_per_epoch=steps_per_epoch,
              validation_steps=validation_steps,
              verbose=2, shuffle=True)

    return model

In [ ]:
#Take a look at the entire code for logistic regression:
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import numpy as np

def load_train(path):
    features_train = np.load(path + 'train_features.npy')
    target_train = np.load(path + 'train_target.npy')
    features_train = features_train.reshape(features_train.shape[0], 28 * 28) / 255.
    return features_train, target_train

def create_model(input_shape):
    model = Sequential()
    model.add(Dense(10, input_shape=input_shape, activation='softmax'))
    model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy',
                  metrics=['acc'])

    return model

def train_model(model, train_data, test_data, batch_size=32, epochs=5,
               steps_per_epoch=None, validation_steps=None):

    features_train, target_train = train_data
    features_test, target_test = test_data
    model.fit(features_train, target_train, 
              validation_data=(features_test, target_test),
              batch_size=batch_size, epochs=epochs,
              steps_per_epoch=steps_per_epoch,
              validation_steps=validation_steps,
              verbose=2, shuffle=True)

    return model

## Convolution Neural Networks

### One-dimensional convolution:

In [9]:
#Let's express a one-dimensional convolution in Python
def convolve(sequence, weights):
    convolution = np.zeros(len(sequence) - len(weights) + 1)
    for i in range(convolution.shape[0]):
        convolution[i] = np.sum(np.array(weights) * np.array(sequence[i:i + len(weights)]))
    return convolution

In [10]:
s = [2, 3, 5, 7, 11]
w = [-1, 1]

In [11]:
convolve(s, w)

array([1., 2., 2., 4.])

In [13]:
convolution = np.zeros(len(s) - len(w) + 1)
convolution

array([0., 0., 0., 0.])

In [16]:
convolution.shape[0]

4

In [18]:
np.array(s[1:1 + len(w)])

array([3, 5])

### Two-dimensional Convolution:

In [20]:
s = [[1, 1, 1, 0, 0],
     [0, 1, 1, 1, 0],
     [0, 0, 1, 1, 1],
     [0, 0, 1, 1, 0],
     [0, 1, 1, 0, 0]]

w = [[1, 0, 1],
     [0, 1, 0],
     [1, 0, 1]]

In [21]:
c = [[0, -3], [7, 13]]

### Convolutional layers in Keras

In [ ]:
keras.layers.Conv2D(filters, kernel_size, strides, padding, activation)

- Here's what all the parameters mean:
    - **filters**: The number of filters, which corresponds to the size of the output tensor.
    - **kernel_size**: The spatial size of the filter K. Any filter is a tensor with the size K×K×D, where D is equal to the depth of the input image.
    - **strides**: A stride determines how far the filter shifts over the input matrix. It's set to 1 by default.
    - **padding**: This parameter determines the width of the zero padding. There are two types of padding: valid and same. The default type of padding is valid and is equal to zero. Same sets the size of the padding automatically so that the width and height of the output tensor is equal to the width and height of the input tensor.
    - **activation**: This function is applied immediately after the convolution. You can use the activation functions already familiar to you: 'relu' and 'sigmoid'. By default, this parameter is None, i.e. activation is disabled.

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense

model = Sequential()

# this tensor has a size of (None, 32, 32, 3)
# the first dimension defines different objects
# it's set to None because the size of the batch is unknown

model.add(Conv2D(filters=4, kernel_size=(3, 3), input_shape=(32, 32, 3)))

# this tensor has a size of (None, 30, 30, 4)

model.add(Flatten()) #makes the multidimensional into a one dimensional

# this tensor has a size of (None, 3600)
# where 3600 = 30 * 30 * 4

model.add(Dense(...))

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense
import matplotlib.pyplot as plt
import numpy as np


features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')

# Change the image's dimensions and set it to a range of [0, 1].
# While changing the size, you can set one of the dimensions to -1, 
# so that it is calculated automatically
features_train = features_train.reshape(-1, 28, 28, 1) / 255.0
features_test = features_test.reshape(-1, 28, 28, 1) / 255.0

model = Sequential()
# < write code here >
model.add(Conv2D(filters=4, kernel_size=(3, 3), input_shape=(28, 28, 1)))
model.add(Flatten())          
model.add(Dense(10, activation='softmax'))         

model.compile(loss='sparse_categorical_crossentropy', optimizer='sgd', metrics=['acc'])

model.summary()

- conv2D: (None, 26, 26, 4), 40parameters
- flatten (None, 2704), 0params
- dense (None, 10), 27050params
    - total params; 27,090

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense
import matplotlib.pyplot as plt
import numpy as np
features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')
features_train = features_train.reshape(-1, 28, 28, 1) / 255.0
features_test = features_test.reshape(-1, 28, 28, 1) / 255.0
model = Sequential()
model.add(Conv2D(filters=4, kernel_size=(3, 3), padding='same',activation="relu", input_shape=(28, 28, 1)))
model.add(Conv2D(filters=4, kernel_size=(3, 3), strides=2, padding='same',activation="relu"))
model.add(Flatten())
model.add(Dense(units=10, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='sgd', metrics=['acc'])
model.summary()
model.fit(features_train, target_train, epochs=1, verbose=1,
steps_per_epoch=1, batch_size=1)

### LeNet Architecture

In [ ]:
#average pooling in Keras:
keras.layers.AveragePooling2D(pool_size=(2, 2), strides=None, padding='valid', ...)

In [ ]:
#a classic LeNet architecture:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense, MaxPooling2D
import matplotlib.pyplot as plt
import numpy as np


features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')

features_train = features_train.reshape(-1, 28, 28, 1) / 255.0
features_test = features_test.reshape(-1, 28, 28, 1) / 255.0

model = Sequential()
model.add(Conv2D(filters=4, kernel_size=(3, 3), padding='same',
                 activation="relu", input_shape=(28, 28, 1)))
model.add(Conv2D(filters=4, kernel_size=(3, 3), strides=2, padding='same',
                 activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(units=10, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='sgd', metrics=['acc'])
model.summary()
model.fit(features_train, target_train, epochs=1, verbose=1,
          steps_per_epoch=1, batch_size=1)

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Conv2D, Flatten, Dense, AvgPool2D
import matplotlib.pyplot as plt
import numpy as np


features_train = np.load('/datasets/fashion_mnist/train_features.npy')
target_train = np.load('/datasets/fashion_mnist/train_target.npy')
features_test = np.load('/datasets/fashion_mnist/test_features.npy')
target_test = np.load('/datasets/fashion_mnist/test_target.npy')


features_train = features_train.reshape(-1, 28, 28, 1) / 255.0
features_test = features_test.reshape(-1, 28, 28, 1) / 255.0

# < write code here >
model = Sequential()
model.add(Conv2D(6, (5, 5), padding='same', activation='tanh',
                 input_shape=(28, 28, 1)))
model.add(AvgPool2D(pool_size=(2, 2)))
 
model.add(Conv2D(16, (5, 5), padding='valid', activation='tanh'))
model.add(AvgPool2D(pool_size=(2, 2)))
 
model.add(Flatten())
model.add(Dense(120, activation='tanh'))
 
model.add(Dense(84, activation='tanh'))
 
model.add(Dense(10, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='sgd', metrics=['acc'])
model.summary()
model.fit(features_train, target_train, epochs=1, verbose=1,
          steps_per_epoch=1, batch_size=1)

### The Adam Algorithm

In [ ]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', 
              metrics=['acc'])

In [ ]:
#set the algorithm class to configure the hyperparameters:
from tensorflow.keras.optimizers import Adam
optimizer = Adam()

model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', 
              metrics=['acc'])

In [ ]:
#learning rate:
optimizer = Adam(lr=0.01)