### Creating Matrices

In [1]:
import numpy as np

matrix = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np

string0 = np.array([1,2,3])
string1 = np.array([-1,-2,-3])
list_of_vectors = [string0, string1]
matrix_from_vectors = np.array(list_of_vectors)

print(matrix_from_vectors)

[[ 1  2  3]
 [-1 -2 -3]]


In [3]:
import pandas as pd

df = pd.DataFrame({'a': [ 120,  60, 75], 'b': [42, 50, 90]})
matrix = df.values
print(df)
print(matrix)

     a   b
0  120  42
1   60  50
2   75  90
[[120  42]
 [ 60  50]
 [ 75  90]]


In [4]:
import numpy as np

A = np.array([
    [1, 2, 3], 
    [2, 3, 4]])

print('Size:', A.shape)
print('A[1, 2]:', A[1, 2])

Size: (2, 3)
A[1, 2]: 4


In [5]:
import numpy as np

matrix = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9],
    [10,11,12]])

print('Row 0:', matrix[0, :])
print('Column 2:', matrix[:, 2])

Row 0: [1 2 3]
Column 2: [ 3  6  9 12]


In [7]:
import numpy as np

matrix = np.array([[3, 14, 159], [-2, 7, 183]])# < write code here >

print(matrix)

[[  3  14 159]
 [ -2   7 183]]


In [8]:
import numpy as np
import pandas as pd

monday_df = pd.DataFrame({'Minutes': [10, 3, 15, 27, 7], 
                          'Messages': [2, 5, 3, 0, 1], 
                          'Megabytes': [72, 111, 50, 76, 85]})
 
monday = monday_df.values# < write code here >

print(monday)

[[ 10   2  72]
 [  3   5 111]
 [ 15   3  50]
 [ 27   0  76]
 [  7   1  85]]


In [9]:
print(monday[3, :])

[27  0 76]


In [10]:
print(monday[:, 2])

[ 72 111  50  76  85]


### 