### Creating Matrices

In [1]:
import numpy as np

matrix = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np

string0 = np.array([1,2,3])
string1 = np.array([-1,-2,-3])
list_of_vectors = [string0, string1]
matrix_from_vectors = np.array(list_of_vectors)

print(matrix_from_vectors)

[[ 1  2  3]
 [-1 -2 -3]]


In [3]:
import pandas as pd

df = pd.DataFrame({'a': [ 120,  60, 75], 'b': [42, 50, 90]})
matrix = df.values
print(df)
print(matrix)

     a   b
0  120  42
1   60  50
2   75  90
[[120  42]
 [ 60  50]
 [ 75  90]]


In [4]:
import numpy as np

A = np.array([
    [1, 2, 3], 
    [2, 3, 4]])

print('Size:', A.shape)
print('A[1, 2]:', A[1, 2])

Size: (2, 3)
A[1, 2]: 4


In [5]:
import numpy as np

matrix = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9],
    [10,11,12]])

print('Row 0:', matrix[0, :])
print('Column 2:', matrix[:, 2])

Row 0: [1 2 3]
Column 2: [ 3  6  9 12]


In [7]:
import numpy as np

matrix = np.array([[3, 14, 159], [-2, 7, 183]])# < write code here >

print(matrix)

[[  3  14 159]
 [ -2   7 183]]


In [8]:
import numpy as np
import pandas as pd

monday_df = pd.DataFrame({'Minutes': [10, 3, 15, 27, 7], 
                          'Messages': [2, 5, 3, 0, 1], 
                          'Megabytes': [72, 111, 50, 76, 85]})
 
monday = monday_df.values# < write code here >

print(monday)

[[ 10   2  72]
 [  3   5 111]
 [ 15   3  50]
 [ 27   0  76]
 [  7   1  85]]


In [9]:
print(monday[3, :])

[27  0 76]


In [10]:
print(monday[:, 2])

[ 72 111  50  76  85]


### Operations with Matrix Elements

In [11]:
import numpy as np

matrix1 = np.array([
    [1, 2], 
    [3, 4]])

matrix2 = np.array([
    [5, 6], 
    [7, 8]])

print(matrix1 + matrix2)

[[ 6  8]
 [10 12]]


In [12]:
import numpy as np

matrix = np.array([
    [1, 2], 
    [3, 4]])

print(matrix * 2)
print(matrix - 2)

[[2 4]
 [6 8]]
[[-1  0]
 [ 1  2]]


In [14]:
import numpy as np
import pandas as pd

services = ['Minutes', 'Messages', 'Megabytes']

monday = np.array([
    [10, 2, 72],
    [3, 5, 111],
    [15, 3, 50],
    [27, 0, 76],
    [7, 1, 85]])

tuesday = np.array([
    [33, 0, 108],
    [21, 5, 70],
    [15, 2, 15],
    [29, 6, 34],
    [2, 1, 146]])

wednesday = np.array([
    [16, 0, 20],
    [23, 5, 34],
    [5, 0, 159],
    [35, 1, 74],
    [5, 0, 15]])

thursday = np.array([
    [25, 1, 53],
    [15, 0, 26],
    [10, 0, 73],
    [18, 1, 24],
    [2, 2, 24]])

friday = np.array([
    [32, 0, 33],
    [4, 0, 135],
    [2, 2, 21],
    [18, 5, 56],
    [27, 2, 21]])

saturday = np.array([
    [28, 0, 123],
    [16, 5, 165],
    [10, 1, 12],
    [42, 4, 80],
    [18, 2, 20]])

sunday = np.array([
    [30, 4, 243],
    [18, 2, 23],
    [12, 2, 18],
    [23, 0, 65],
    [34, 0, 90]])

weekly = monday + tuesday + wednesday + thursday + friday + saturday + sunday# < write code here >

print('In a week')
print(pd.DataFrame(weekly, columns=services))
print()

forecast = (weekly / 7) * 30

print('Forecast for a month')
print(pd.DataFrame(forecast, dtype=int, columns=services))

In a week
   Minutes  Messages  Megabytes
0      174         7        652
1      100        22        564
2       69        10        348
3      192        17        409
4       95         8        401

Forecast for a month
   Minutes  Messages  Megabytes
0      745        30       2794
1      428        94       2417
2      295        42       1491
3      822        72       1752
4      407        34       1718


### Multiplying a Matrix by a Vector

In [15]:
import numpy as np
    
A = np.array([
    [1, 2, 3], 
    [4, 5, 6]])

b = np.array([7, 8, 9])

print(np.dot(A, b))
print(A.dot(b))

[ 50 122]
[ 50 122]


In [16]:
import numpy as np
import pandas as pd

services = ['Minutes', 'Messages', 'Megabytes']
packs_names = ['"Behind the wheel"', '"On the subway"']
packs = np.array([
    [20, 5],
    [2, 5],
    [500, 1000]])

print('Package content')
print(pd.DataFrame(packs, columns=packs_names, index=services))
print()

clients_packs = np.array([
    [1, 2],
    [2, 3],
    [4, 1],
    [2, 3],
    [5, 0]])

print("Client's packages")
print(pd.DataFrame(clients_packs, columns=packs_names))
print()

Package content
           "Behind the wheel"  "On the subway"
Minutes                    20                5
Messages                    2                5
Megabytes                 500             1000

Client's packages
   "Behind the wheel"  "On the subway"
0                   1                2
1                   2                3
2                   4                1
3                   2                3
4                   5                0



In [29]:
import numpy as np
import pandas as pd

services = ['Minutes', 'Messages', 'Megabytes']
packs_names = ['"Behind the wheel"', '"On the subway"']
packs = np.array([
    [20, 5],
    [2, 5],
    [500, 1000]])

clients_packs = np.array([
    [1, 2],
    [2, 3],
    [4, 1],
    [2, 3],
    [5, 0]])

client = 1
print("Client's package") 
print(pd.DataFrame(clients_packs[client], index=packs_names, columns=['']))
print()

#client_vector = clients_packs[client, :]
client_vector = clients_packs[1, :]
client_services = np.dot(packs, client_vector)

print("Minutes, Messages, Megabytes")
print(client_vector)
print(packs)
print(client_services)

Client's package
                     
"Behind the wheel"  2
"On the subway"     3

Minutes, Messages, Megabytes
[2 3]
[[  20    5]
 [   2    5]
 [ 500 1000]]
[  55   19 4000]


### Transpose of a Matrix

In [30]:
import numpy as np

matrix = np.array([
    [1, 2], 
    [4, -4], 
    [0, 17]])

print("Original matrix")
print(matrix)
print("Transposed matrix")
print(matrix.T)

Original matrix
[[ 1  2]
 [ 4 -4]
 [ 0 17]]
Transposed matrix
[[ 1  4  0]
 [ 2 -4 17]]


In [31]:
vector = [2, 1, -1]
print(np.dot(matrix, vector))

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

In [32]:
print(np.dot(matrix.T, vector))

[  6 -17]


In [33]:
Item    Board,pcs   Pipe, m  Screw, number 
 Chair           0.2       1.2       8
 Bench           0.5       0.8       6
 Table           0.8       1.6       8

SyntaxError: invalid syntax (<ipython-input-33-c71ff1eccaa7>, line 1)

In [37]:
import numpy  as np
import pandas as pd

materials_names = ['Wooden board', 'Metal pipe', 'Screws']

manufacture = np.array([
    [0.2, 1.2, 8],
    [0.5, 0.8, 6],
    [0.8, 1.6, 8]])

furniture = [60, 4, 16]

#materials = np.dot(manufacture, furniture)# < write code here >
materials = np.dot(manufacture.T, furniture)

print(pd.DataFrame([materials_2], index=[''], columns=materials_names))

  Wooden board  Metal pipe  Screws
          26.8       100.8   632.0


### Matrix Multiplication

In [38]:
import numpy as np
    
A = np.array([
    [1, 2, 3], 
    [-1, -2, -3]])

B = np.array([
    [1, 0], 
    [0, 1],
    [1, 1]])

print(A.dot(B))
print(np.dot(A,B)) 
print(A @ B)

[[ 4  5]
 [-4 -5]]
[[ 4  5]
 [-4 -5]]
[[ 4  5]
 [-4 -5]]


In [40]:
print(B)

[[1 0]
 [0 1]
 [1 1]]


In [41]:
print(B @ A)

[[ 1  2  3]
 [-1 -2 -3]
 [ 0  0  0]]


In [43]:
matrix = np.array([
    [1, 2, 3], 
    [-1, -2, -3]])

print(matrix @ matrix)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [44]:
#Multiplying the matrix by itself is only possible if it is square:
square_matrix = np.array([
    [1, 2, 3], 
    [-1, -2, -3],
    [0, 0, 0]])

print(square_matrix @ square_matrix)

[[-1 -2 -3]
 [ 1  2  3]
 [ 0  0  0]]


In [45]:
costs = np.array([
    [700, 50] 
])

In [46]:
bookings_1 = np.array([
    [3, 4], # number of bookings for honeymoon suites in February and March
    [17, 26] # number of bookings for regular rooms in February and March
])

bookings_2 = np.array([
    [8, 9, 11], # number of bookings for honeymoon suites in June, July and August
    [21, 26, 30] # number of bookings for regular rooms in June, July and August
])

In [48]:
import numpy as np
import pandas as pd

months_1 = ['February', 'March']
months_2 = ['June', 'July', 'August']

costs = np.array([
    # honeymoon_suite, regular
    [700, 50]
])

bookings_1 = np.array([
    [3, 4],
    [17, 26]
])

bookings_2 = np.array([
    [8, 9, 11],
    [21, 26, 30]
])

print(pd.DataFrame((costs @ bookings_1), columns=months_1))
print('----------------------')
print(pd.DataFrame((costs @ bookings_2), columns=months_2))

   February  March
0      2950   4100
----------------------
   June  July  August
0  6650  7600    9200


In [54]:
import numpy as np
import pandas as pd

services = ['Minutes', 'Messages', 'Megabytes']
packs_names = ['"Behind the wheel', '"On the subway"']
packs = np.array([
    [20, 5],
    [2, 5],
    [500, 1000]])

clients_packs = np.array([
    [1, 2],
    [2, 3],
    [4, 1],
    [2, 3],
    [5, 0]])

print('Packages')
print(pd.DataFrame(clients_packs, columns=packs_names))
print()

clients_services = (packs.dot(clients_packs.T).T)# < write code here >

print('Minutes, Messages and Megabytes')
print(pd.DataFrame(clients_services, columns=services))
print()
#print(clients_servicew)

Packages
   "Behind the wheel  "On the subway"
0                  1                2
1                  2                3
2                  4                1
3                  2                3
4                  5                0

Minutes, Messages and Megabytes
   Minutes  Messages  Megabytes
0       30        12       2500
1       55        19       4000
2       85        13       3000
3       55        19       4000
4      100        10       2500



In [53]:
packs.dot(clients_packs.T)

array([[  30,   55,   85,   55,  100],
       [  12,   19,   13,   19,   10],
       [2500, 4000, 3000, 4000, 2500]])

In [56]:
import numpy  as np
import pandas as pd

materials_names = ['Wooden board', 'Metal pipe', 'Screws']
venues_names = ['Coffee shop', 'Diner', 'Restaurant']

manufacture = np.array([
    [0.2, 1.2, 8],
    [0.5, 0.8, 6],
    [0.8, 1.6, 8]])

furniture = np.array([
    [12, 0, 3],
    [40, 2, 10],
    [60, 6, 18]])

venues_materials = furniture @ manufacture# < write code here >

print('By the venue')
print(pd.DataFrame(venues_materials, index=venues_names, columns=materials_names))
print()

venues = [18, 12, 7]

total_materials = venues @ venues_materials# < write code here >

print('Total')
print(pd.DataFrame([total_materials], index=[''], columns=materials_names))

By the venue
             Wooden board  Metal pipe  Screws
Coffee shop           4.8        19.2   120.0
Diner                17.0        65.6   412.0
Restaurant           29.4       105.6   660.0

Total
  Wooden board  Metal pipe   Screws
         496.2      1872.0  11724.0
